using System.Numerics;
using Content.AL.UIKit.Styleboxes;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySongPanel.PanelOverride = HullrotPanel();
            LobbyBackgroundPanel.PanelOverride = HullrotPanel();
            RightSide.PanelOverride = HullrotPanel();
            LeftSideTop.PanelOverride = HullrotPanel();

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
        }

        private static StyleboxExtruded HullrotPanel()
        {
            var baseBox = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1A1A1AEE"),
                BorderColor = Color.FromHex("#D6B36A"),
                BorderThickness = new Thickness(2),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            };

            return new StyleboxExtruded(
                baseBox,
                new Vector2(4, 4),
                modulate: Color.FromHex("#050505AA")
            );
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;

                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                        RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup,
        }
    }
}
